"""Curated MITRE ATT&CK technique reference - practical triage notes for
the techniques most likely to show up in real alerts, not a mirror of
MITRE's own (much larger) site. Each entry is written for "what does this
mean when I see it in a ticket," not academic completeness.
"""

from __future__ import annotations

MITRE_TECHNIQUES: dict[str, dict] = {
    "T1055": {
        "name": "Process Injection",
        "tactic": "Defense Evasion / Privilege Escalation",
        "what_it_is": "Malicious code runs inside the memory space of a legitimate, already-running process, instead of as its own visible process.",
        "looks_like_in_practice": "An EDR alert naming a normal process (svchost.exe, explorer.exe) but flagging anomalous memory regions, unexpected threads, or outbound network activity that process doesn't normally do.",
        "common_false_positive": "Some legitimate security/monitoring software and DRM also inject into other processes - check the injecting process's own reputation before assuming malice.",
        "next_step": "Identify the injecting process and the target process. Memory-dump and hash analysis on the injected region if your EDR supports it.",
    },
    "T1003": {
        "name": "OS Credential Dumping",
        "tactic": "Credential Access",
        "what_it_is": "Extracting stored credentials (hashes, plaintext passwords, Kerberos tickets) from OS memory or files - classically LSASS memory on Windows.",
        "looks_like_in_practice": "A process (often a renamed or unusual binary) accessing lsass.exe memory, or known tool signatures (Mimikatz-style behavior) in EDR telemetry.",
        "common_false_positive": "Legitimate backup/AV software occasionally reads LSASS for unrelated reasons - rare, but check the process's signer before assuming compromise.",
        "next_step": "Treat as a high-confidence compromise indicator. Assume any credentials on that host are burned - reset them, don't just monitor.",
    },
    "T1486": {
        "name": "Data Encrypted for Impact (ransomware)",
        "tactic": "Impact",
        "what_it_is": "Files are being encrypted en masse, typically the final stage of a ransomware deployment.",
        "looks_like_in_practice": "Mass file-extension changes, sudden spike in file-write/rename operations, or shadow-copy deletion happening at the same time.",
        "common_false_positive": "Legitimate full-disk encryption rollouts or large compression/backup jobs can superficially resemble this - check timing and whether it was scheduled/expected.",
        "next_step": "This is an active incident, not a ticket to triage calmly - isolate immediately, this is one of the few cases where speed matters more than process.",
    },
    "T1021": {
        "name": "Remote Services (lateral movement)",
        "tactic": "Lateral Movement",
        "what_it_is": "Using legitimate remote access protocols (RDP, SMB, SSH, WinRM) to move from one compromised host to another.",
        "looks_like_in_practice": "A login to a new host using credentials that just authenticated somewhere else, especially off-hours or from a host that doesn't normally connect there.",
        "common_false_positive": "IT/helpdesk remote support and legitimate automation (scheduled jobs, config management) use the same protocols constantly - context (which account, which hosts, what time) is everything here.",
        "next_step": "Map which hosts the account touched and in what order - this tells you the scope, not just the entry point.",
    },
    "T1078": {
        "name": "Valid Accounts",
        "tactic": "Initial Access / Persistence / Privilege Escalation / Defense Evasion",
        "what_it_is": "Using legitimate, valid credentials rather than exploiting a vulnerability - the account itself is real, just being used by someone who shouldn't have it.",
        "looks_like_in_practice": "Impossible travel, login from a new/unusual device or location, or activity inconsistent with the account owner's normal role.",
        "common_false_positive": "VPN exit-node geolocation quirks, new personal devices, and legitimate travel all produce the same surface signals - verify with the user before escalating.",
        "next_step": "Confirm with the account owner directly. If they didn't do it, treat this as a credential compromise, not just an anomaly.",
    },
    "T1190": {
        "name": "Exploit Public-Facing Application",
        "tactic": "Initial Access",
        "what_it_is": "Exploiting a vulnerability in an internet-facing application (web app, VPN gateway, API) to gain initial access.",
        "looks_like_in_practice": "Unusual request patterns in web/WAF logs, a known CVE's exploit signature, or a public-facing service spawning unexpected child processes.",
        "common_false_positive": "Vulnerability scanners (including your own org's) generate similar traffic patterns - confirm the source IP isn't an authorized scanner first.",
        "next_step": "Check whether the application is patched for the relevant CVE. If exploited successfully, assume the application's service account is compromised.",
    },
    "T1071": {
        "name": "Application Layer Protocol (C2)",
        "tactic": "Command and Control",
        "what_it_is": "Malware communicating with its command-and-control server disguised as normal application traffic (HTTP/S, DNS, etc.) to blend in.",
        "looks_like_in_practice": "Regular, periodic outbound connections (beaconing) to an uncommon or newly-registered domain, especially at suspiciously consistent intervals.",
        "common_false_positive": "Legitimate software update checkers and telemetry/analytics SDKs also beacon periodically - check domain age and reputation (the IOC Enrichment API in this same SOC Lab) before escalating.",
        "next_step": "Check the destination domain's age and reputation. A domain registered days ago receiving regular check-ins from one host is a strong signal.",
    },
    "T1547": {
        "name": "Boot or Logon Autostart Execution (persistence)",
        "tactic": "Persistence",
        "what_it_is": "Configuring something to run automatically at boot/logon - registry Run keys, startup folder entries, scheduled tasks - so malware survives a reboot.",
        "looks_like_in_practice": "A new registry Run key or startup-folder entry pointing to an unsigned binary, or one located in an unusual path (temp folders, user-writable directories).",
        "common_false_positive": "Plenty of legitimate software (chat apps, cloud sync clients) registers autostart entries too - check signer and path, not just the existence of the entry.",
        "next_step": "Identify what the persisted binary actually is, then remove the persistence mechanism as part of remediation - don't just kill the running process.",
    },
    "T1562": {
        "name": "Impair Defenses",
        "tactic": "Defense Evasion",
        "what_it_is": "Disabling or tampering with security tools - AV/EDR, logging, firewall rules - so the rest of the attack goes unnoticed.",
        "looks_like_in_practice": "EDR/AV service stopped or uninstalled unexpectedly, Windows Defender exclusions added without a change ticket, or log clearing (see T1070) around the same time.",
        "common_false_positive": "IT-driven AV migrations/updates can look identical - check for an associated, authorized change record before assuming malice.",
        "next_step": "This is almost always a sign something else is already happening - treat it as a strong escalation signal on its own, then look for what it was covering for.",
    },
    "T1566": {
        "name": "Phishing",
        "tactic": "Initial Access",
        "what_it_is": "Using a deceptive email (or message) to get a user to click a link, open an attachment, or hand over credentials.",
        "looks_like_in_practice": "A reported suspicious email - the Phishing Triage Bot in this same SOC Lab handles full evidence-based analysis of these directly.",
        "common_false_positive": "Legitimate marketing/notification emails with urgent-sounding subject lines get reported constantly - check sender authentication (SPF/DKIM/DMARC) before assuming malice.",
        "next_step": "If a link was clicked or credentials entered, treat as Valid Accounts (T1078) territory - reset credentials regardless of how convincing the phish looked.",
    },
    "T1059": {
        "name": "Command and Scripting Interpreter",
        "tactic": "Execution",
        "what_it_is": "Using a command-line shell or scripting engine (PowerShell, cmd.exe, bash, Python) to execute commands - the single most common execution method in real intrusions, sub-technique .001 (PowerShell) especially.",
        "looks_like_in_practice": "PowerShell with encoded/obfuscated arguments, unusual parent-child process chains (Office app spawning cmd.exe), or scripting engines invoked by a process that doesn't normally need them.",
        "common_false_positive": "IT automation and legitimate admin scripts use the exact same interpreters constantly - the parent process and argument patterns matter far more than the interpreter itself.",
        "next_step": "Decode any encoded command-line arguments before judging intent - obfuscation itself (see T1027) is often more telling than the decoded content.",
    },
    "T1053": {
        "name": "Scheduled Task/Job",
        "tactic": "Persistence",
        "what_it_is": "Creating a scheduled task or cron job so a payload runs again later or repeatedly - a classic, easy-to-miss persistence mechanism.",
        "looks_like_in_practice": "A newly-created scheduled task with an unusual name, pointing to a script/binary in a non-standard location, or running with elevated privileges it shouldn't need.",
        "common_false_positive": "Legitimate software installers create scheduled tasks routinely (update checkers, license validation) - check what the task actually runs, not just that one exists.",
        "next_step": "Always check what the task is set to RUN, not just that it exists - the task name is attacker-controlled and easy to make look benign.",
    },
    "T1548": {
        "name": "Abuse Elevation Control Mechanism",
        "tactic": "Privilege Escalation / Defense Evasion",
        "what_it_is": "Bypassing or abusing the OS's own privilege-elevation prompts (UAC bypass on Windows, sudo misuse on Linux) to run with higher privileges without a clean authorized prompt.",
        "looks_like_in_practice": "A process gaining administrator/SYSTEM privileges without a corresponding UAC prompt event, or known UAC-bypass technique signatures in EDR telemetry.",
        "common_false_positive": "Some legitimate installers use documented (if unusual) elevation methods - check if the binary is signed and from a known vendor.",
        "next_step": "Identify what the elevated process did with its new privileges - that's the actual impact, the bypass itself is just the means.",
    },
    "T1027": {
        "name": "Obfuscated Files or Information",
        "tactic": "Defense Evasion",
        "what_it_is": "Encoding, encrypting, or otherwise disguising malicious code/commands so static detection and human review don't immediately recognize them.",
        "looks_like_in_practice": "Base64-encoded PowerShell arguments, packed/high-entropy executable sections (the File Analyser in this same SOC Lab flags this directly), or strings that look like meaningless character soup.",
        "common_false_positive": "Legitimate commercial software packers (for IP protection, not malice) produce similar high-entropy signatures - reputation/signing matters more than entropy alone.",
        "next_step": "Decode/unpack before judging - obfuscation is itself a strong signal of intent to evade, even before you know what's inside.",
    },
    "T1036": {
        "name": "Masquerading",
        "tactic": "Defense Evasion",
        "what_it_is": "Making a malicious file or process look legitimate - naming it after a real Windows system file, placing it in a similar-looking path, or disguising its actual file type (the File Analyser in this same SOC Lab catches this directly via magic-byte vs extension mismatch).",
        "looks_like_in_practice": "A file named svchost.exe running from a non-system directory, or a file with a .pdf extension that's actually a PE executable.",
        "common_false_positive": "Genuinely rare to have an innocent explanation - this is one of the more reliable individual signals when confirmed.",
        "next_step": "Compare the file's actual hash/signature against the legitimate version it's impersonating, and check its running location.",
    },
    "T1070": {
        "name": "Indicator Removal",
        "tactic": "Defense Evasion",
        "what_it_is": "Deleting or tampering with logs, command history, or other forensic evidence to cover tracks after an action.",
        "looks_like_in_practice": "Windows Event Log service stopped/cleared, bash history cleared mid-session, or timestamps on files that don't match their content's expected creation time.",
        "common_false_positive": "Scheduled log rotation/retention policies can look similar - check whether the clearing aligns with a known, authorized retention schedule.",
        "next_step": "Treat as a strong indicator something happened just before the gap - focus investigation on the time window immediately preceding the log gap.",
    },
    "T1110": {
        "name": "Brute Force",
        "tactic": "Credential Access",
        "what_it_is": "Repeatedly guessing passwords (or spraying one common password across many accounts) to gain access - extremely common, and the SOC Incident Tracker's own seeded SOP for this covers it directly.",
        "looks_like_in_practice": "Many failed logins in a short window, from one source or against one account, sometimes followed by a single success.",
        "common_false_positive": "A user who forgot their password and is retrying, or a misconfigured service account with a stale credential, produce the same pattern - check if ANY attempt succeeded before assuming attack.",
        "next_step": "The single most important question is whether any attempt succeeded - that changes this from a perimeter-noise ticket into a confirmed-compromise ticket.",
    },
    "T1082": {
        "name": "System Information Discovery",
        "tactic": "Discovery",
        "what_it_is": "An attacker (or their tool) querying basic system info - OS version, hostname, installed software, hardware - almost always one of the first things done after gaining a foothold.",
        "looks_like_in_practice": "Commands like systeminfo, whoami, or similar discovery commands run shortly after an initial access event, often scripted/batched.",
        "common_false_positive": "IT inventory/asset-management tools run identical commands routinely and constantly - check if this is a known, scheduled inventory scan.",
        "next_step": "Rarely meaningful alone - its value is in what it's clustered with. Check what happened immediately before and after.",
    },
    "T1570": {
        "name": "Lateral Tool Transfer",
        "tactic": "Lateral Movement",
        "what_it_is": "Copying tools (or malware) from one compromised host to another, usually via SMB/admin shares, to extend the attacker's foothold.",
        "looks_like_in_practice": "An executable or script appearing on a second host shortly after suspicious activity on a first one, often via the same account, transferred over SMB.",
        "common_false_positive": "Legitimate software deployment tools (SCCM, similar) push files the same way - check whether it matches an authorized deployment window.",
        "next_step": "This is the clearest signal of active spread - check every host the same file/hash has touched, not just the two you already know about.",
    },
    "T1105": {
        "name": "Ingress Tool Transfer",
        "tactic": "Command and Control",
        "what_it_is": "Downloading additional tools or malware onto a compromised host from an external source, after initial access.",
        "looks_like_in_practice": "An outbound connection followed immediately by a new file appearing on disk, especially via certutil, bitsadmin, or PowerShell download cradles.",
        "common_false_positive": "Legitimate software auto-updaters do the same thing - check the destination domain's reputation and the binary's signature once downloaded.",
        "next_step": "Hash and check reputation on whatever was downloaded (the IOC Enrichment API/File Analyser in this same SOC Lab) before deciding severity.",
    },
    "T1490": {
        "name": "Inhibit System Recovery",
        "tactic": "Impact",
        "what_it_is": "Deleting backups, shadow copies, or other recovery mechanisms - a strong ransomware tell, usually done right before or during encryption (T1486).",
        "looks_like_in_practice": "vssadmin delete shadows, wbadmin commands deleting backup catalogs, or backup software/services being disabled.",
        "common_false_positive": "Legitimate disk-space cleanup of old shadow copies happens, but rarely targets ALL of them at once or coincides with other suspicious activity.",
        "next_step": "If seen alongside any other suspicious activity on the same host, treat as an active ransomware precursor - escalate immediately, don't wait for encryption to start.",
    },
    "T1595": {
        "name": "Active Scanning",
        "tactic": "Reconnaissance",
        "what_it_is": "An attacker probing your internet-facing infrastructure (port scans, vulnerability scans) before attempting any actual exploitation.",
        "looks_like_in_practice": "A burst of connection attempts across many ports/IPs in your range, or WAF/firewall logs showing systematic probing patterns from one source.",
        "common_false_positive": "Your own org's authorized vulnerability scanner, or a benign third-party internet-scanning project (Shodan, Censys) - check the source IP against known scanner ranges first.",
        "next_step": "Note the source and what it was looking for - if it later shows up as the source of a real exploit attempt (T1190), this was the reconnaissance phase of the same campaign.",
    },
    "T1589": {
        "name": "Gather Victim Identity Information",
        "tactic": "Reconnaissance",
        "what_it_is": "An attacker collecting employee names, emails, roles, or org-chart info ahead of a targeted phish or password-spray campaign - usually from LinkedIn, breach dumps, or company websites.",
        "looks_like_in_practice": "Rarely seen directly in your own telemetry - it's usually inferred AFTER the fact, when a phishing or spraying campaign turns out to be precisely targeted at specific roles (finance, IT admins).",
        "common_false_positive": "N/A - this happens outside your visibility by definition; the \"false positive\" risk is over-attributing a generic/untargeted attack to deliberate recon it didn't actually involve.",
        "next_step": "If a phishing/spray campaign is suspiciously well-targeted, note it - it suggests this is a deliberate campaign against your org, not opportunistic mass-mailing.",
    },
    "T1133": {
        "name": "External Remote Services",
        "tactic": "Initial Access / Persistence",
        "what_it_is": "Using legitimate remote-access services exposed to the internet (VPN, RDP, Citrix, any remote-access gateway) to get in - directly relevant to the GP-VPN Brute Force Attempts rule in this tracker's Rule Book.",
        "looks_like_in_practice": "A successful login to a VPN/remote-access gateway from an unusual location, especially right after a string of failed attempts (T1110) against the same or related accounts.",
        "common_false_positive": "Legitimate remote workers traveling, or a new device enrolling for the first time - verify with the user before treating as compromise.",
        "next_step": "Check whether MFA was actually enforced on this login - a lot of External Remote Services compromises succeed specifically because MFA was missing or bypassed (see T1621).",
    },
    "T1195": {
        "name": "Supply Chain Compromise",
        "tactic": "Initial Access",
        "what_it_is": "Compromise introduced via a trusted third party - a software vendor's update mechanism, an open-source package, or a managed service provider with access into your environment.",
        "looks_like_in_practice": "Malicious activity that traces back to a legitimate, signed software update or a dependency your team didn't write, rather than anything a user clicked or downloaded directly.",
        "common_false_positive": "A vendor's legitimate but unannounced update can trigger the same alert pattern - check the vendor's own security bulletins before assuming compromise.",
        "next_step": "Identify the exact component/version implicated and check public advisories - if it's a known supply-chain incident, your IOCs/timeline will likely match published reports.",
    },
    "T1204": {
        "name": "User Execution",
        "tactic": "Execution",
        "what_it_is": "The attack depends on a user directly running something - opening an attachment, clicking a link that downloads a file, or running a script they were tricked into trusting.",
        "looks_like_in_practice": "A user-initiated process launch (double-clicked file) immediately followed by suspicious child-process activity, often right after a phishing email (T1566) was opened.",
        "common_false_positive": "Plenty of legitimate files require the same click-to-run action - the suspicious part is always what happens AFTER execution, not the click itself.",
        "next_step": "Trace back to delivery (email, download, USB) - User Execution is almost never the full story, just the entry point of a longer chain.",
    },
    "T1047": {
        "name": "Windows Management Instrumentation",
        "tactic": "Execution / Lateral Movement",
        "what_it_is": "Using WMI (wmic.exe, PowerShell's WMI cmdlets) to execute commands locally or remotely - a built-in admin tool frequently abused because it's already trusted and present everywhere.",
        "looks_like_in_practice": "wmic process call create, or remote WMI calls between hosts that don't normally use this for legitimate management.",
        "common_false_positive": "Systems-management tools (SCCM, monitoring agents) use WMI constantly and legitimately - check whether the calling account/host matches your known management infrastructure.",
        "next_step": "Look at what command WMI was used to actually run - the technique itself is neutral, the payload is what matters.",
    },
    "T1098": {
        "name": "Account Manipulation",
        "tactic": "Persistence",
        "what_it_is": "Modifying an existing account to maintain access - adding it to a privileged group, adding a new MFA device/method, or changing its permissions.",
        "looks_like_in_practice": "A new MFA device registered for an account without a corresponding helpdesk ticket, or an account suddenly added to an admin group outside normal change windows.",
        "common_false_positive": "Legitimate self-service MFA re-enrollment after a lost phone, or an authorized access-request workflow - check for a matching ticket/approval before escalating.",
        "next_step": "Confirm with the account owner AND check the change against your change-management record - an unexplained privilege change on its own is enough to escalate.",
    },
    "T1136": {
        "name": "Create Account",
        "tactic": "Persistence",
        "what_it_is": "Creating a brand-new local or domain account, often with an innocuous name, as a backup access method independent of whatever account got the attacker in initially.",
        "looks_like_in_practice": "A new account creation event outside onboarding workflows, sometimes added directly to an admin/privileged group at creation time.",
        "common_false_positive": "Legitimate new-hire onboarding or service-account creation for a new application - check against HR/change records first.",
        "next_step": "If unexplained, disable immediately and check what that account did between creation and discovery - assume it was used.",
    },
    "T1505": {
        "name": "Server Software Component (web shells)",
        "tactic": "Persistence",
        "what_it_is": "Dropping a malicious script (web shell) onto a web server so the attacker can keep running commands through it, independent of whatever vulnerability got them in originally - common follow-up after Exploit Public-Facing Application (T1190).",
        "looks_like_in_practice": "A new, unexpected file in a web-accessible directory, or web server logs showing repeated requests to one unusual-looking script with command-like parameters.",
        "common_false_positive": "Legitimate admin/debug scripts left behind by developers can look superficially similar - check file age against the last known-good deployment.",
        "next_step": "Pull the file and review its contents directly - web shells are usually small enough to fully read, and that tells you exactly what capability the attacker has.",
    },
    "T1068": {
        "name": "Exploitation for Privilege Escalation",
        "tactic": "Privilege Escalation",
        "what_it_is": "Exploiting a software vulnerability specifically to go from a low-privileged foothold to admin/SYSTEM/root, rather than abusing a misconfiguration (see T1548).",
        "looks_like_in_practice": "A crash or unusual behavior in a privileged process immediately followed by that process (or a child of it) gaining elevated rights, often correlating with a known local-privilege-escalation CVE.",
        "common_false_positive": "Genuine application crashes happen for unrelated reasons - the distinguishing signal is privilege gain immediately following the crash, not the crash alone.",
        "next_step": "Check patch level against the suspected CVE. If unpatched and exploited, this host needs the same urgency as a confirmed compromise.",
    },
    "T1112": {
        "name": "Modify Registry",
        "tactic": "Defense Evasion",
        "what_it_is": "Changing Windows registry values to hide configuration, disable security features, or support persistence - a generic mechanism underlying many other techniques.",
        "looks_like_in_practice": "Registry changes to security-relevant keys (Defender exclusions, Run keys, LSA settings) outside of a known config-management push.",
        "common_false_positive": "Group Policy and legitimate software installers modify the registry constantly - the specific KEY matters far more than the fact a change happened at all.",
        "next_step": "Identify exactly which key changed and what it controls - that tells you whether this enabled persistence, evasion, or something benign.",
    },
    "T1218": {
        "name": "System Binary Proxy Execution (LOLBins)",
        "tactic": "Defense Evasion",
        "what_it_is": "Using a legitimate, signed Windows binary (rundll32, mshta, certutil, regsvr32) to run malicious code indirectly - because the binary itself is trusted, this often slips past naive allow-listing.",
        "looks_like_in_practice": "certutil.exe used with -decode/-urlcache flags (its built-in download capability, not its intended cert function), or rundll32 invoking an unusual DLL export.",
        "common_false_positive": "These binaries do have legitimate uses - certutil for actual certificate operations, rundll32 for normal DLL calls - the command-line ARGUMENTS are what distinguish abuse from normal use.",
        "next_step": "Always read the full command line, not just the binary name - that's where LOLBin abuse reveals itself.",
    },
    "T1497": {
        "name": "Virtualization/Sandbox Evasion",
        "tactic": "Defense Evasion / Discovery",
        "what_it_is": "Malware checking whether it's running inside a sandbox/VM/analysis environment, and altering or halting its behavior if so - meant to defeat automated analysis, not your live environment directly.",
        "looks_like_in_practice": "Usually only visible in malware analysis output (the File Analyser in this same SOC Lab may flag VM-detection strings) rather than live host telemetry.",
        "common_false_positive": "Legitimate software occasionally checks for virtualization for licensing/performance reasons - context (is this a known malicious sample?) matters more than the check itself.",
        "next_step": "If a submitted file shows sandbox-evasion behavior, treat that alone as a meaningful maliciousness signal - legitimate software rarely needs to hide its true behavior.",
    },
    "T1140": {
        "name": "Deobfuscate/Decode Files or Information",
        "tactic": "Defense Evasion",
        "what_it_is": "The malware itself decoding/decrypting its own payload at runtime - the inverse side of Obfuscated Files (T1027): something was hidden, and this is the step where it gets revealed to actually run.",
        "looks_like_in_practice": "A process writing a new, larger file or memory region right after reading a smaller encoded one - common in multi-stage droppers.",
        "common_false_positive": "Legitimate self-extracting archives and installers do this too - the surrounding context (was the encoded blob suspicious to begin with?) is what matters.",
        "next_step": "Try to capture the decoded output before it's cleaned up - that's the actual payload you need to analyze, the encoded form tells you little on its own.",
    },
    "T1552": {
        "name": "Unsecured Credentials",
        "tactic": "Credential Access",
        "what_it_is": "Finding credentials that were never properly secured in the first place - hardcoded in scripts/config files, left in plaintext notes, or stored in shell history.",
        "looks_like_in_practice": "Access to files like .env, config.php, or shell history shortly after a host compromise, especially if those files contain recognizable credential patterns.",
        "common_false_positive": "Routine access to config files by the application itself isn't suspicious - the concern is an attacker/unusual process reading them.",
        "next_step": "If any credential exposure is confirmed, rotate it immediately regardless of whether you can prove it was actually used - assume burned.",
    },
    "T1557": {
        "name": "Adversary-in-the-Middle",
        "tactic": "Credential Access / Collection",
        "what_it_is": "Intercepting traffic between two parties to steal credentials or session data - ARP spoofing, rogue Wi-Fi APs, or malicious proxy/relay configs.",
        "looks_like_in_practice": "Unexpected ARP table changes, a device suddenly routing through an unfamiliar gateway, or browser warnings about certificate mismatches reported by users.",
        "common_false_positive": "Legitimate corporate proxies/TLS-inspection appliances produce similar certificate-substitution signals - confirm against your own known-good infrastructure list first.",
        "next_step": "If confirmed on a network segment, assume every credential used on that segment during the window is compromised - this isn't a single-account issue.",
    },
    "T1111": {
        "name": "Multi-Factor Authentication Interception",
        "tactic": "Credential Access",
        "what_it_is": "Capturing or intercepting an MFA code/token in transit - SMS interception, a malicious proxy sitting between the user and the real MFA prompt, or a compromised MFA device itself.",
        "looks_like_in_practice": "A successful MFA-backed login from a location/device inconsistent with the user's normal pattern, with no record of the user reporting an unusual prompt.",
        "common_false_positive": "Carrier-level SMS delivery delays/duplicates can look unusual but aren't malicious - corroborate with the login's other risk signals before escalating.",
        "next_step": "If interception is suspected, move the account off SMS-based MFA to an authenticator-app or hardware-key method as part of remediation, not just a password reset.",
    },
    "T1621": {
        "name": "Multi-Factor Authentication Request Generation (MFA fatigue/bombing)",
        "tactic": "Credential Access",
        "what_it_is": "Repeatedly triggering MFA push prompts to a user, hoping they approve one out of frustration or confusion - the attacker already has the password, this is the last step to get past MFA. Directly covered by the PingID MFA Spamming rule in this tracker's Rule Book.",
        "looks_like_in_practice": "A burst of MFA push notifications to one user in a short window, especially outside their normal working hours.",
        "common_false_positive": "Multiple devices/browser tabs legitimately retrying one real login attempt - check the actual count and pattern, a true fatigue attack is usually many more prompts than that.",
        "next_step": "Confirm with the user whether they approved anything - ANY approval means treat the account as compromised and reset credentials regardless of how the prompts started.",
    },
    "T1087": {
        "name": "Account Discovery",
        "tactic": "Discovery",
        "what_it_is": "Enumerating valid user/group accounts in the environment - usually one of the first things done after gaining a foothold, to find better targets for lateral movement or privilege escalation.",
        "looks_like_in_practice": "Commands like net user, net group, or LDAP queries enumerating large numbers of accounts, especially from a host that doesn't normally do this.",
        "common_false_positive": "IT/helpdesk tools and directory-sync services do this constantly and legitimately - check whether the source matches known admin tooling.",
        "next_step": "Rarely actionable alone - note it, then watch for what technique follows (often T1078 or T1021 against whatever it found).",
    },
    "T1018": {
        "name": "Remote System Discovery",
        "tactic": "Discovery",
        "what_it_is": "Mapping out other hosts on the network - ping sweeps, ARP scans, querying DNS/AD for a host inventory - to plan lateral movement.",
        "looks_like_in_practice": "A burst of connection attempts to many internal IPs in sequence from one host, especially to ports not normally used by that host's legitimate role.",
        "common_false_positive": "Network monitoring/asset-discovery tools do exactly this on a schedule - check if the timing matches a known scan window.",
        "next_step": "Note which subnets/hosts were discovered - that's your hypothesis for where lateral movement will be attempted next.",
    },
    "T1069": {
        "name": "Permission Groups Discovery",
        "tactic": "Discovery",
        "what_it_is": "Enumerating security/permission groups (local or domain) to figure out which accounts are worth targeting for further privilege escalation.",
        "looks_like_in_practice": "net localgroup administrators or equivalent AD group-membership queries run from a host shortly after initial access.",
        "common_false_positive": "IT audit/compliance tooling runs these queries routinely - check against known scheduled audit jobs.",
        "next_step": "Same as Account Discovery - low value alone, but tells you what the attacker now knows about your privilege structure.",
    },
    "T1057": {
        "name": "Process Discovery",
        "tactic": "Discovery",
        "what_it_is": "Listing running processes on a host - often used to check for security tooling (EDR, AV) before deciding next steps, or to find a process worth injecting into.",
        "looks_like_in_practice": "tasklist or Get-Process executed shortly after a suspicious initial-access event, sometimes immediately followed by Impair Defenses (T1562) if security tooling was found.",
        "common_false_positive": "Completely normal admin/troubleshooting activity - only meaningful in the context of what happened immediately before/after.",
        "next_step": "Check whether it was followed by an attempt to stop/evade anything it found - that's the real signal, not the enumeration itself.",
    },
    "T1119": {
        "name": "Automated Collection",
        "tactic": "Collection",
        "what_it_is": "A script or tool automatically gathering files/data of interest (by file type, keyword, or location) rather than an attacker manually browsing - lets them collect at scale quickly.",
        "looks_like_in_practice": "A burst of file-read operations across many directories in a short time, often targeting specific extensions (.docx, .xlsx, .pdf) or folder names (Finance, HR).",
        "common_false_positive": "Legitimate backup or search-indexing software does similar bulk reads - check whether the process is a known backup agent first.",
        "next_step": "Identify what was collected and where it was staged - this tells you what's at risk before any exfiltration even happens.",
    },
    "T1114": {
        "name": "Email Collection",
        "tactic": "Collection",
        "what_it_is": "Accessing a mailbox's contents beyond what's needed for normal use - bulk-reading emails, setting up forwarding rules, or using a compromised token to pull mail via API.",
        "looks_like_in_practice": "A new mail-forwarding rule the user didn't create, or API/mailbox-access logs showing bulk message retrieval inconsistent with normal client behavior - check this specifically as part of the Azure Risky Sign-in rule's investigation steps.",
        "common_false_positive": "Legitimate mail-migration tools or e-discovery/legal-hold processes access mail in bulk too - confirm against any known, authorized migration window.",
        "next_step": "Check for forwarding rules FIRST - removing a malicious one is more urgent than analyzing how it got there.",
    },
    "T1056": {
        "name": "Input Capture",
        "tactic": "Collection",
        "what_it_is": "Capturing user input directly - keylogging, or a fake login form (web-based input capture) designed to harvest credentials as they're typed.",
        "looks_like_in_practice": "A process hooking keyboard input APIs, or a phishing page mimicking a real login form (often flagged by the Phishing Triage Bot's heuristics in this same SOC Lab).",
        "common_false_positive": "Legitimate accessibility software and some enterprise input tools use similar hooking APIs - check digital signature/reputation of the hooking process.",
        "next_step": "Assume every credential typed on the affected host/page during the active window is compromised - reset accordingly, don't just remove the capture mechanism.",
    },
    "T1572": {
        "name": "Protocol Tunneling",
        "tactic": "Command and Control",
        "what_it_is": "Wrapping C2 traffic inside another protocol (DNS tunneling is the classic example) to sneak it past firewalls that only inspect/allow specific protocols.",
        "looks_like_in_practice": "An unusually high volume of DNS queries to one domain, with abnormally long or encoded-looking subdomains - a strong DNS-tunneling signature.",
        "common_false_positive": "Some legitimate CDN/anti-DDoS services use unusual DNS patterns - check domain reputation and query volume against your normal baseline.",
        "next_step": "If DNS tunneling is confirmed, the registered domain itself is your best pivot point - block it and check every host that's queried it.",
    },
    "T1090": {
        "name": "Proxy",
        "tactic": "Command and Control",
        "what_it_is": "Routing C2 traffic through an intermediate system (compromised host, public proxy, Tor) to hide the real C2 server's location and make blocking harder.",
        "looks_like_in_practice": "Outbound connections to a known proxy/Tor exit-node IP range, or one internal host relaying traffic for others that shouldn't be acting as a relay.",
        "common_false_positive": "Legitimate corporate proxy infrastructure is, by definition, doing the same thing - make sure the proxy in question isn't your own sanctioned one.",
        "next_step": "Block the proxy/relay endpoint, but don't stop there - the REAL C2 server is still hidden behind it; treat this as one hop, not the destination.",
    },
    "T1102": {
        "name": "Web Service (C2 via legitimate platforms)",
        "tactic": "Command and Control",
        "what_it_is": "Using a legitimate, trusted web service (GitHub, Pastebin, Google Docs, Discord, Slack) to host C2 instructions or exfiltrate data, since traffic to these domains rarely gets blocked.",
        "looks_like_in_practice": "A host making repeated, scripted-looking requests to a trusted platform's API or raw-content URLs, especially from a process that has no legitimate reason to use that service.",
        "common_false_positive": "Genuinely high false-positive risk - tons of legitimate software legitimately calls these same platforms. The calling PROCESS and pattern (periodic, scripted) matter far more than the destination domain.",
        "next_step": "Don't bother trying to block the platform itself (you'll break legitimate use org-wide) - focus on the specific process/host making the suspicious calls.",
    },
    "T1041": {
        "name": "Exfiltration Over C2 Channel",
        "tactic": "Exfiltration",
        "what_it_is": "Sending stolen data out through the same channel already being used for command-and-control, rather than opening a separate connection.",
        "looks_like_in_practice": "A sudden spike in outbound data volume on an already-flagged beaconing connection (see T1071), rather than a new destination appearing.",
        "common_false_positive": "Legitimate large uploads (backups, telemetry) on that same channel if it's actually a sanctioned service - confirm the channel was already confirmed malicious before treating volume spikes as exfil.",
        "next_step": "Quantify the volume and try to determine what data classification was involved - that's what drives legal/compliance notification obligations, not just confirming the technique.",
    },
    "T1567": {
        "name": "Exfiltration Over Web Service",
        "tactic": "Exfiltration",
        "what_it_is": "Uploading stolen data to a legitimate cloud storage/file-sharing service (Google Drive, Dropbox, Mega) rather than a dedicated C2 server - blends in with normal SaaS usage.",
        "looks_like_in_practice": "A large, unusual upload to a personal cloud-storage account from a corporate host/account, especially one not on your sanctioned SaaS list.",
        "common_false_positive": "Employees legitimately backing up personal files to personal cloud storage on a work device - a policy violation, but not necessarily malicious; check data sensitivity and volume before treating as a breach.",
        "next_step": "Identify exactly what was uploaded before deciding severity - the destination being \"legitimate\" doesn't change what matters: what left, and how sensitive it was.",
    },
    "T1048": {
        "name": "Exfiltration Over Alternative Protocol",
        "tactic": "Exfiltration",
        "what_it_is": "Moving stolen data out using a protocol other than the main C2 channel - FTP, raw sockets, or email - sometimes specifically to avoid triggering monitoring tuned only for the main C2 protocol.",
        "looks_like_in_practice": "An outbound FTP/SFTP session or unusual raw-socket transfer from a host that doesn't normally do this, carrying a large volume of data.",
        "common_false_positive": "Legitimate scheduled FTP-based data transfers to partners/vendors - confirm against known integration/automation jobs before escalating.",
        "next_step": "Same as any exfiltration finding: quantify volume and data classification first, channel/protocol is secondary to what actually left.",
    },
    "T1485": {
        "name": "Data Destruction",
        "tactic": "Impact",
        "what_it_is": "Deliberately deleting or corrupting data/systems - distinct from ransomware's encryption (T1486), this is destruction with no recovery key offered at all, sometimes used to cover tracks or as pure sabotage.",
        "looks_like_in_practice": "Mass file deletions or disk-wiping utility activity, often alongside Inhibit System Recovery (T1490) to make sure there's no backup to fall back on either.",
        "common_false_positive": "Legitimate decommissioning/wipe processes on retiring hardware - confirm against your asset-disposal schedule before treating as an incident.",
        "next_step": "This is an active, time-critical incident - prioritize containment and recovery-source verification over investigation sequencing.",
    },
    "T1531": {
        "name": "Account Access Removal",
        "tactic": "Impact",
        "what_it_is": "Locking legitimate users out - mass password resets, account disabling, or deleting accounts outright - sometimes as the final, disruptive stage of an attack rather than data theft.",
        "looks_like_in_practice": "A burst of password resets or account-disable actions across many accounts in a short window, not matching any planned IT maintenance.",
        "common_false_positive": "A genuine bulk password-reset campaign (post-breach precaution, compliance-driven rotation) - confirm against IT's own change calendar first.",
        "next_step": "Get affected users back into their accounts as the immediate priority, then investigate which admin credential was used to do this - that account is now your primary suspect.",
    },
    "T1499": {
        "name": "Endpoint Denial of Service",
        "tactic": "Impact",
        "what_it_is": "Overwhelming a specific service/application/host so it becomes unavailable - distinct from a network-level DDoS, this targets an application's own resource limits.",
        "looks_like_in_practice": "A specific service crashing or becoming unresponsive under unusually high request volume or malformed input, while the rest of the network looks fine.",
        "common_false_positive": "A genuine, unplanned traffic spike (viral content, legitimate load spike) - check whether the request pattern looks deliberately malformed/abusive versus just high-volume.",
        "next_step": "Identify the resource being exhausted (CPU, memory, connection pool, a specific API endpoint) - that tells you whether rate-limiting or a code fix is the real remediation, not just restarting the service.",
    },
}


def get_technique(technique_id: str) -> dict | None:
    return MITRE_TECHNIQUES.get(technique_id.strip().upper())


def list_techniques() -> list[dict]:
    return [{"id": tid, **data} for tid, data in sorted(MITRE_TECHNIQUES.items())]


def search_techniques(query: str) -> list[dict]:
    query = query.strip().lower()
    return [
        t for t in list_techniques()
        if query in t["id"].lower() or query in t["name"].lower() or query in t["tactic"].lower()
    ]
