"""Reference content pulled from GAP Cyber Defense's actual SOP documents,
one entry per SOP number. These are full multi-page operational runbooks
(L1/L2/L3 steps, dozens of full Splunk queries per alert type, field
mapping tables) - this module deliberately does NOT reproduce the raw
Splunk queries verbatim (there are dozens, often a full page each, and
this app doesn't execute Splunk queries so embedding them adds bulk
without function). What's captured is the lookup-useful summary an
analyst actually wants when they type an alert name in: which SOP it
belongs to, when L1 hands off to L2, when L2 escalates to L3, this SOP's
specific phrasing of the 5 disposition verdicts, the ServiceNow action ->
queue routing table, and a few worked closure examples for calibration.

Add a new key here as each additional real SOP PDF is provided (13 total
expected, arriving in batches) - REAL_SOP_REFERENCE.get(sop_id) returning
None for a not-yet-added SOP is the expected/handled case, not an error.
"""

from __future__ import annotations

GAP_CONTACTS: list[dict] = [
    {"name": "Haiwei Wong", "email": "haiwei_wong@gap.com",
     "use_case": "Manager exceptions, senior-manager+ communications, management decision visibility"},
    {"name": "Jim Riley", "email": "jim_riley@gap.com",
     "use_case": "Manager exceptions, senior-manager+, SLT confirmation"},
    {"name": "Raj Thomas", "email": "raj_thomas@gap.com", "use_case": "Escalation contact"},
    {"name": "Tom Le", "email": "Tom@gap.com", "use_case": "Escalation contact"},
]

REAL_SOP_REFERENCE: dict[str, dict] = {
    "SOP-01": {
        "title": "VPN, Authentication, Brute Force & Password Spraying Investigation and Response",
        "rules_covered": [
            "GP-VPN Password Spraying", "GP-VPN Brute Force Attempts",
            "Windows Failed Logon on Disabled Account", "O365 Activity from Anonymous Proxy",
            "PAN GP-VPN Unofficial Client",
        ],
        "l1_escalation_triggers": [
            "Successful authentication is observed.",
            "Multiple users are targeted.",
            "One user has high failed attempts.",
            "Disabled account attempts are repeated.",
            "Anonymous proxy is involved.",
            "Unofficial VPN client is observed.",
            "Source IP is suspicious, foreign, proxy-based, cloud-hosted, or threat-listed.",
            "User is privileged, VIP, service account, or sensitive.",
            "Multiple related alerts exist.",
            "Required fields are missing.",
            "Endpoint evidence is suspicious.",
            "L1 cannot confidently classify the activity as benign.",
        ],
        "l3_escalation_triggers": [
            "Confirmed credential compromise.",
            "Successful authentication after password spray or brute force.",
            "Suspicious MFA success or MFA bypass.",
            "Privileged account impact.",
            "VIP / SLT / C-Suite impact.",
            "Critical asset impact.",
            "Large-scale attack.",
            "Lateral movement suspected.",
            "Endpoint compromise suspected.",
            "Business-impacting remediation required.",
            "P1/P2 incident may be required.",
        ],
        "verdict_guidance": {
            "Malicious": "Confirmed attack, compromise, or hostile activity",
            "Unresolved-suspicious": "Suspicious activity remains but compromise is not confirmed",
            "Policy violation": "Legitimate user/system activity violates policy",
            "Authorized": "Activity is approved with valid durable evidence",
            "Benign-other": "Activity is not malicious and not policy violation",
        },
        "servicenow_routing": [
            {"action": "IP block", "queue": "PT-DATA CENTER NETWORK"},
            {"action": "Account disable", "queue": "PT-Identity Access Management / PT-Access Management"},
            {"action": "Password reset", "queue": "SOC Team / IAM"},
            {"action": "Force password reset", "queue": "IAM Team"},
            {"action": "Endpoint investigation / containment", "queue": "PT-EDR Platform"},
            {"action": "Reimage machine", "queue": "Local Deskside Team"},
            {"action": "Email sender block", "queue": "Messaging Team / GAP L3"},
            {"action": "URL / domain block", "queue": "PT-Infrastructure Security"},
            {"action": "Detection tuning", "queue": "Jira to SIEM Team"},
        ],
        "closure_examples": [
            {"scenario": "Password Spray with No Successful Login", "activity": "Confirmed",
             "verdict": "Unresolved-suspicious or Benign-other", "detection_quality": "Working",
             "closure_owner": "L2",
             "note": "Multiple users targeted from one source IP. No successful authentication observed. No account action required."},
            {"scenario": "Brute Force with Successful Login", "activity": "Confirmed",
             "verdict": "Malicious or Unresolved-suspicious", "detection_quality": "Working",
             "closure_owner": "L3 if compromise is suspected",
             "note": "Multiple failures followed by successful authentication. MFA reviewed. Escalated to L3."},
            {"scenario": "Disabled Account Stale Credential", "activity": "Confirmed",
             "verdict": "Benign-other", "detection_quality": "Working", "closure_owner": "L2",
             "note": "Disabled account failures observed from known workstation. No success observed."},
            {"scenario": "O365 Anonymous Proxy Successful Access", "activity": "Confirmed",
             "verdict": "Unresolved-suspicious or Malicious", "detection_quality": "Working",
             "closure_owner": "L2 or L3 depending on impact",
             "note": "O365 access from anonymous proxy confirmed. Escalated if compromise suspected."},
            {"scenario": "Unofficial VPN Client Approved Exception", "activity": "Confirmed",
             "verdict": "Authorized", "detection_quality": "Context gap", "closure_owner": "L2",
             "note": "Unofficial client activity validated as approved exception using durable evidence."},
        ],
        "gap_contacts": GAP_CONTACTS,
    },
    "SOP-02": {
        "title": "MFA Abuse, Bypass, Spamming & Authentication-Process Change Investigation and Response",
        "rules_covered": [
            "PingID Potential MFA Spamming", "HDDT MFA Bypass Detection",
            "HDDT Anomalous MFA Activity", "PingID MFA Device Added After Reset",
            "O365 MFA Conditional Access Policy Modified",
        ],
        "l1_escalation_triggers": [
            "MFA prompt was approved after repeated prompts.",
            "MFA bypass is observed.",
            "Suspicious MFA method or factor is observed.",
            "New MFA device was added after reset.",
            "Conditional Access policy was modified.",
            "Source IP is suspicious, foreign, proxy-based, cloud-hosted, or threat-listed.",
            "User is privileged, VIP, service account, or sensitive.",
            "Multiple related alerts exist.",
            "Required fields are missing.",
            "L1 cannot confidently classify the activity as benign.",
        ],
        "l3_escalation_triggers": [
            "Confirmed account takeover.",
            "MFA prompt approved after MFA spamming.",
            "MFA bypass resulted in successful authentication.",
            "Unauthorized MFA device enrollment.",
            "Unauthorized Conditional Access policy modification.",
            "MFA enforcement weakened for multiple users.",
            "Privileged account impact.",
            "VIP / SLT / C-Suite impact.",
            "Critical asset or business-critical application impact.",
            "Suspicious mailbox, OAuth, Teams, SharePoint, or OneDrive activity after MFA success.",
            "Large-scale attack.",
            "Business-impacting remediation required.",
            "P1/P2 incident may be required.",
        ],
        "verdict_guidance": {
            "Malicious": "Confirmed account takeover, MFA bypass abuse, unauthorized MFA device enrollment, or unauthorized policy weakening",
            "Unresolved-suspicious": "Suspicious MFA activity remains but compromise is not confirmed",
            "Policy violation": "Legitimate user/system activity violates policy",
            "Authorized": "Activity is approved with valid durable evidence",
            "Benign-other": "Activity is not malicious and not policy violation",
        },
        "servicenow_routing": [
            {"action": "User account disable / enable", "queue": "PT-Identity Access Management / PT-Access Management"},
            {"action": "Password reset", "queue": "SOC Team"},
            {"action": "Force password reset", "queue": "IAM Team"},
            {"action": "MFA reset / re-enrollment", "queue": "PT-Authentication / IAM"},
            {"action": "Remove unauthorized MFA device", "queue": "PT-Authentication / IAM"},
            {"action": "Conditional Access policy review / rollback", "queue": "PT-Authentication / IAM"},
            {"action": "IP block", "queue": "PT-DATA CENTER NETWORK"},
            {"action": "Endpoint containment", "queue": "PT-EDR Platform"},
            {"action": "Email sender block", "queue": "Messaging Team / GAP L3"},
            {"action": "Detection tuning", "queue": "Jira to SIEM Team"},
        ],
        "closure_examples": [
            {"scenario": "MFA Spamming with No Approval", "activity": "Confirmed",
             "verdict": "Unresolved-suspicious or Benign-other", "detection_quality": "Working",
             "closure_owner": "L2",
             "note": "Multiple MFA prompts observed. No prompt approval or successful login observed. No account action required."},
            {"scenario": "MFA Spamming with Approved Prompt", "activity": "Confirmed",
             "verdict": "Malicious or Unresolved-suspicious", "detection_quality": "Working",
             "closure_owner": "L3 if compromise is suspected",
             "note": "MFA prompt was approved after repeated MFA prompts. Escalated to L3 for compromise validation."},
            {"scenario": "MFA Bypass with Successful Authentication", "activity": "Confirmed",
             "verdict": "Malicious", "detection_quality": "Working", "closure_owner": "L3",
             "note": "MFA bypass resulted in successful authentication. L3 engaged."},
            {"scenario": "MFA Device Added After Approved Reset", "activity": "Confirmed",
             "verdict": "Authorized", "detection_quality": "Context gap", "closure_owner": "L2",
             "evidence_reference_required": "ServiceNow or change record",
             "note": "MFA reset and new device enrollment validated using durable approval evidence."},
            {"scenario": "Unauthorized Conditional Access Policy Change", "activity": "Confirmed",
             "verdict": "Malicious or Policy violation", "detection_quality": "Working",
             "closure_owner": "L3 if policy weakening or broad impact exists",
             "note": "Conditional Access policy modification confirmed. No valid change record found. Policy rollback routed through ServiceNow."},
        ],
        "gap_contacts": GAP_CONTACTS,
    },
    "SOP-03": {
        "title": "Risky Sign-in, Identity Risk & Identity Compromise Investigation and Response",
        "rules_covered": [
            "Azure Risky Signin", "Permiso High Severity Alert", "PingID Suspicious Activity Risk Logs",
            "CrowdStrike Identity Protection Critical", "Permiso Critical Severity Alert",
        ],
        "l1_escalation_triggers": [
            "Risky sign-in succeeded.",
            "Risk level is high or critical.",
            "Permiso alert is high or critical.",
            "CrowdStrike Identity Protection Critical is triggered.",
            "Source IP is suspicious, foreign, proxy-based, cloud-hosted, or threat-listed.",
            "New country, new ASN, or impossible travel is observed.",
            "User is privileged, VIP, service account, or sensitive.",
            "Multiple related alerts exist.",
            "Session ID is present and may have been used.",
            "Required fields are missing.",
            "Endpoint evidence is suspicious.",
            "L1 cannot confidently classify the activity as benign.",
        ],
        "l3_escalation_triggers": [
            "Confirmed account takeover.",
            "Risky sign-in succeeded and session was used.",
            "Privileged account impact.",
            "VIP / SLT / C-Suite impact.",
            "Service account or break-glass account impact.",
            "Critical asset or business-critical application impact.",
            "CrowdStrike Identity Protection Critical confirms identity attack.",
            "Permiso Critical alert confirms sensitive identity misuse.",
            "Suspicious mailbox, OAuth, Teams, SharePoint, or OneDrive activity after successful sign-in.",
            "Endpoint compromise suspected.",
            "Lateral movement suspected.",
            "Large-scale attack.",
            "Business-impacting remediation required.",
            "P1/P2 incident may be required.",
        ],
        "verdict_guidance": {
            "Malicious": "Confirmed account takeover, identity attack, risky session abuse, or unauthorized use of a valid account",
            "Unresolved-suspicious": "Suspicious identity activity remains but compromise is not confirmed",
            "Policy violation": "Legitimate user/system activity violates policy",
            "Authorized": "Activity is approved with valid durable evidence",
            "Benign-other": "Activity is not malicious and not policy violation",
        },
        "servicenow_routing": [
            {"action": "User account disable / enable", "queue": "PT-Identity Access Management / PT-Access Management"},
            {"action": "Password reset", "queue": "SOC Team"},
            {"action": "Force password reset", "queue": "IAM Team"},
            {"action": "Session/token revocation", "queue": "PT-Authentication / IAM"},
            {"action": "MFA reset / re-enrollment", "queue": "PT-Authentication / IAM"},
            {"action": "Cloud security review", "queue": "PT-Cloud Security"},
            {"action": "IP block", "queue": "PT-DATA CENTER NETWORK"},
            {"action": "Endpoint containment", "queue": "PT-EDR Platform"},
            {"action": "Email sender block", "queue": "Messaging Team / GAP L3"},
        ],
        "closure_examples": [
            {"scenario": "Azure Risky Sign-In, No Successful Login", "activity": "Confirmed",
             "verdict": "Benign-other or Unresolved-suspicious", "detection_quality": "Working",
             "closure_owner": "L2",
             "note": "Risky sign-in alert validated. No successful authentication or session usage observed."},
            {"scenario": "Risky Sign-In with Session Usage", "activity": "Confirmed",
             "verdict": "Malicious or Unresolved-suspicious", "detection_quality": "Working",
             "closure_owner": "L3 if compromise is suspected",
             "note": "Risky sign-in succeeded and session was used. Escalated to L3."},
            {"scenario": "PingID Suspicious Activity from Known Travel / VPN", "activity": "Confirmed",
             "verdict": "Authorized or Benign-other", "detection_quality": "Context gap", "closure_owner": "L2",
             "evidence_reference_required": "ServiceNow, travel approval, or approved business context",
             "note": "PingID suspicious activity validated as expected user activity from known travel/VPN context."},
            {"scenario": "CrowdStrike Identity Protection Critical for Privileged User", "activity": "Confirmed",
             "verdict": "Malicious or Unresolved-suspicious", "detection_quality": "Working", "closure_owner": "L3",
             "note": "CrowdStrike Identity Protection Critical alert confirmed for privileged user. L3 engaged."},
            {"scenario": "Permiso Critical Alert with Privileged Cloud Activity", "activity": "Confirmed",
             "verdict": "Malicious", "detection_quality": "Working", "closure_owner": "L3",
             "note": "Permiso Critical identity finding confirmed. Privileged cloud activity observed. L3 engaged."},
        ],
        "gap_contacts": GAP_CONTACTS,
    },
}


def get_sop_reference(sop_id: str) -> dict | None:
    return REAL_SOP_REFERENCE.get(sop_id)
